# Generated by Django 3.2.7 on 2022-02-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.CharField(max_length=100)),
                ('kid_age', models.IntegerField()),
                ('parent_phone_number', models.CharField(max_length=12)),
                ('parent_email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('approoved_by', models.CharField(max_length=100)),
                ('food_group', models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('GRAIN', 'Grain'), ('DAIRY', 'Dairy'), ('PROTIEN', 'Protien'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kids')),
            ],
        ),
    ]
