# Generated by Django 3.2.7 on 2022-02-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
