# Generated by Django 3.2.7 on 2022-02-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_alter_image_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
